version: '3.8'

services:
  surveysvc-broker:
    image: apache/kafka:4.0.0
    volumes:
      - kafka-data:/tmp
    hostname: surveysvc-broker
    container_name: surveysvc-broker
    ports:
      - '9092:9092'
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://surveysvc-broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@surveysvc-broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
  surveysvc-db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=datab
    ports:
      - '5432:5432'

  surveysvc-consumer:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@surveysvc-db:5432/datab
      - KAFKA_BROKER_URI=surveysvc-broker:9092
      - KAFKA_CONSUMER_TOPIC=surveyx-answers
      - KAFKA_DEADLETTER_TOPIC=surveyx-answers-dead
      - KAFKA_CONSUMER_GROUP=surveyx-answers-consumers
    volumes:
      - app-vol:/root
      - type: bind
        source: './'
        target: '/surveysvc'
    depends_on:
      - surveysvc-db
      - surveysvc-broker
    command: ['go', 'run', './cmd/consumer/main.go']

  surveysvc:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '50052:50052'
      - '50053:50053'
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@surveysvc-db:5432/datab
    volumes:
      - app-vol:/root
      - type: bind
        source: './'
        target: '/surveysvc'
    depends_on:
      - surveysvc-db
volumes:
  postgres_data:
  app-vol:
  kafka-data:
