// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Answer struct {
	ID             uuid.UUID
	SelectedOption pgtype.Text
	AnswerText     pgtype.Text
	UserID         uuid.UUID
	QuestionID     uuid.UUID
	QuestionSetID  uuid.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type QuestionMapping struct {
	ID         uuid.UUID
	QuestionID uuid.UUID
	CampaignID uuid.UUID
	OrgID      uuid.UUID
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
