// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Answer struct {
	ID             uuid.UUID          `json:"id"`
	SelectedOption pgtype.Text        `json:"selected_option"`
	AnswerText     pgtype.Text        `json:"answer_text"`
	UserID         uuid.UUID          `json:"user_id"`
	QuestionID     uuid.UUID          `json:"question_id"`
	QuestionSetID  uuid.UUID          `json:"question_set_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type QuestionMapping struct {
	ID         uuid.UUID          `json:"id"`
	QuestionID uuid.UUID          `json:"question_id"`
	CampaignID uuid.UUID          `json:"campaign_id"`
	OrgID      uuid.UUID          `json:"org_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
